### ISSUE TITLE
Missing dependency on rxjs

### ISSUE THREAD

**Issue by jcristovao** [nuintun/inquirer-datepicker#1]
Hello,
I'm getting an error when I try to run this very simple code:

```
    return inquirer.prompt(
      [ { type: 'datepicker'
        , name: 'startOfLowSeason'
        , message: 'When does the low season start? '
        }
      ]
```

I've noticed this module uses `rxjs` (although it's missing from the `package.json`), so I've tried to install it, but I still get an error:

```
Unhandled rejection TypeError: dest.addListener is not a function
    at RefCountObservable.observableProto.pipe (/home/work/node_modules/rx/dist/rx.backpressure.js:595:10)
    at Datepicker._run (/home/work/node_modules/inquirer-datepicker/index.js:307:10)
    at Datepicker.<anonymous> (/home/work/node_modules/inquirer/lib/prompts/base.js:56:10)
    at executorPatched (/home/work/node_modules/cls-bluebird/lib/shimOnCancel.js:37:21)
    at Promise._execute (/home/work/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/work/node_modules/bluebird/js/release/promise.js:481:18)
    at Promise._resolveFromExecutor (/home/work/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
    at new Promise (/home/work/node_modules/bluebird/js/release/promise.js:77:14)
    at Datepicker.Prompt.run (/home/work/node_modules/inquirer/lib/prompts/base.js:55:10)
    at module.exports.<anonymous> (/home/work/node_modules/inquirer/lib/ui/prompt.js:78:56)
    at tryCatcher (/home/work/node_modules/rx/dist/rx.js:63:31)
    at Defer.subscribeCore (/home/work/node_modules/rx/dist/rx.js:2536:37)
    at Defer.tryCatcher (/home/work/node_modules/rx/dist/rx.js:63:31)
    at setDisposable (/home/work/node_modules/rx/dist/rx.js:2082:46)
    at Defer.Rx.ObservableBase.ObservableBase._subscribe (/home/work/node_modules/rx/dist/rx.js:2097:9)
    at Defer.Rx.Observable.observableProto.subscribe.observableProto.forEach (/home/work/node_modules/rx/dist/rx.js:2034:19)
```

Any clue on what the problem may be?

Thank you

**Comment by nuintun** [comment]
Only support `inquirer>=6.0.0`!  And also you can try version `2.0.0`.
